spring:
  thymeleaf.cache: false

server:
  servlet:
    context-path: /test

logging:
  config: classpath:log-config.xml

# This value is inyected for an example
index:
  view.text:
    greeting: Hello World!

spring.datasource.url: jdbc:h2:data_files