spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
    url: jdbc:h2:file:~/spring-boot-groovy
  h2:
    console:
      enabled: true
      path: /console

# To use gorm you need this configuration at this level
hibernate:
  hbm2ddl:
    auto: create-drop # update

server:
  context-path: /test

logging:
  config: classpath:log-config.xml

# This value is inyected for an example
index:
  view.text:
    greeting: Hello World!
